baseURL = "https://example.com/"
languageCode = "en-us"
title = "Jared Murphy"
# theme = "your-theme-here"

[params]
  author = "Jared Murphy"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "photography"
    name = "Photography"
    url = "/photography/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/#about"
    weight = 4
